server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/onclass_user
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${secret}
logging:
  level:
    org:
      springframework:
        security: TRACE